# Generated by Django 4.0 on 2022-01-11 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_products_created_at_products_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
